spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quiz?serverTimezone=Asia/Seoul
    username: quiz
    password: 1234
